# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.6
  terraform: circleci/terraform@3.2.0
# Define a job to be invoked later in a workflow.

jobs:
  get-artifact:
    steps:
      - run:
          name: Get artifacts
          when: on_fail
          command: |
            artifacts=$(curl -X GET "https://circleci.com/api/v2/project/github/KenKaprielian/Example-Stack/$CIRCLE_BUILD_NUM/artifacts" \
            -H "Accept: application/json" \
            -u "$kentoken:")
            # generate a heredoc in BASH_ENV
            # the '\<<' is a CircleCI escape
            echo "read -r -d '' STORED_ARTIFACTS \<< 'EOF_ARTIFACTS'" >> $BASH_ENV
            echo "$artifacts" >> $BASH_ENV
            echo "EOF_ARTIFACTS" >> $BASH_ENV
            
  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION_NAME
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: .
      - terraform/apply:
          path: .
      - store_artifacts:
          path: ./terraform.tfstate
          destination: terraform.tfstate
    working_directory: ~/src
workflows:
  aws-cli:
    jobs:
      - aws-cli-cred-setup:
          context: aws
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle
