name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
      run: |
        aws --version
        (
          sleep .5
          echo "${{ secrets.AWS_ACCESS_KEY_ID }}"
          sleep .5
          echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          sleep .5
          echo "us-east-1"
          sleep .5
          echo "json"
        ) | aws configure
        
        
        (
          sleep .5
          echo ""
          sleep .5
          echo ""
          sleep .5
          echo ""
          sleep .5
          echo ""
        ) | aws configure
        
        echo "secret: ${{ secrets.access_key }}"
        
        cat ~/.aws/config
        ls -a
    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true

    - name: Terraform Apply
      id: Apply
      run: terraform apply -auto-approve
      continue-on-error: false
